/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "ProxyChatBridge"

include(":dist")
include(":common")
include(":bukkit")
include(":bungee")
include(":velocity")

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
}