/*
 * This file was generated by the Gradle 'init' task.
 */

import net.minecrell.pluginyml.bukkit.BukkitPluginDescription

plugins {
    id("com.ranull.java-conventions")
    id("net.minecrell.plugin-yml.bukkit") version "0.5.2"
}

dependencies {
    compileOnly(project(":common"))
    compileOnly("io.papermc.paper", "paper-api", "1.19.3-R0.1-SNAPSHOT")
    compileOnly("com.github.Moulberry:adventure-binary-serializer:master-SNAPSHOT")
    compileOnly("at.helpch:api:1.0-SNAPSHOT")
}

bukkit {
    main = "com.ranull.proxychatbridge.bukkit.ProxyChatBridge"
    name = "ProxyChatBridge"
    version = "${project.version}"
    apiVersion = "1.19"
    authors = listOf("Nailm", "Ranull")
    softDepend = listOf("ChatChat")
    permissions {
        register("proxychatbridge.broadcast") {
            description = "Server wide broadcast"
            default = BukkitPluginDescription.Permission.Default.OP
        }
    }
    commands {
        register("proxychatbridgebukkitbroadcast") {
            description = "Server wide broadcast"
            aliases = listOf("pcbbb")
            usage = "/<command>"
        }
    }
}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
