/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ranull.java-conventions")
}

dependencies {}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
