/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ranull.java-conventions")
    id("net.minecrell.plugin-yml.bungee") version "0.5.2"
}

dependencies {
    compileOnly(project(":common"))
    compileOnly("net.md-5", "bungeecord-api", "1.19-R0.1-SNAPSHOT")
}

bungee {
    name = "ProxyChatBridge"
    version = "${project.version}"
    description = project.description
    main = "com.ranull.proxychatbridge.bungee.ProxyChatBridge"
    author = "Nailm"
}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
