/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.ranull.java-conventions")
}

dependencies {
    compileOnly(project(":common"))
    compileOnly("com.velocitypowered", "velocity-api", "3.1.2-SNAPSHOT")
    annotationProcessor("com.velocitypowered", "velocity-api", "3.1.2-SNAPSHOT")
}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
